"""WebIntelPro Enterprise X - Live Chat / Customer Messaging Fingerprints"""

FINGERPRINTS = [
    {"name": "Intercom", "category": "chat", "headers": [], "meta": [],
     "scripts": ["widget.intercom.io", "js.intercomcdn.com"],
     "inline": ["intercomsettings", "window.intercom"], "dom": ["intercom-"],
     "cookies": ["intercom-id", "intercom-session"]},
    {"name": "Drift", "category": "chat", "headers": [], "meta": [],
     "scripts": ["js.driftt.com", "drift.com"], "inline": ["drift.load", "window.drift"],
     "dom": ["drift-"], "cookies": ["driftt_aid"]},
    {"name": "Zendesk Chat", "category": "chat", "headers": [], "meta": [],
     "scripts": ["static.zdassets.com", "zopim.com", "zendesk"],
     "inline": ["zopim", "zesettings", "window.zendesk"], "dom": [], "cookies": ["__zlcmid"]},
    {"name": "LiveChat", "category": "chat", "headers": [], "meta": [],
     "scripts": ["cdn.livechatinc.com", "livechatinc.com"],
     "inline": ["__lc", "window.livechat"], "dom": ["livechat-"], "cookies": []},
    {"name": "Tawk.to", "category": "chat", "headers": [], "meta": [],
     "scripts": ["embed.tawk.to", "tawk.to"], "inline": ["tawk_api", "$_tawk"],
     "dom": ["tawk-"], "cookies": []},
    {"name": "Crisp", "category": "chat", "headers": [], "meta": [],
     "scripts": ["client.crisp.chat", "crisp.chat"],
     "inline": ["$crisp", "crisp_website_id"], "dom": ["crisp-client"], "cookies": []},
    {"name": "Tidio", "category": "chat", "headers": [], "meta": [],
     "scripts": ["code.tidio.co", "tidio.co"], "inline": ["tidiochatapi", "window.tidio"],
     "dom": ["tidio-"], "cookies": []},
    {"name": "Freshchat", "category": "chat", "headers": [], "meta": [],
     "scripts": ["wchat.freshchat.com", "freshchat"],
     "inline": ["fcwidget", "window.fcwidget"], "dom": ["freshchat-", "fc_frame"],
     "cookies": []},
    {"name": "Olark", "category": "chat", "headers": [], "meta": [],
     "scripts": ["static.olark.com", "olark.com"], "inline": ["olark", "olark.identify"],
     "dom": ["olark-"], "cookies": []},
    {"name": "Gorgias", "category": "chat", "headers": [], "meta": [],
     "scripts": ["config.gorgias.chat", "gorgias.chat"],
     "inline": ["gorgias", "window.gorgias"], "dom": ["gorgias-chat"], "cookies": []},
    {"name": "HubSpot Chat", "category": "chat", "headers": [], "meta": [],
     "scripts": ["js.usemessages.com"], "inline": ["hubspotconversations"],
     "dom": ["hubspot-messages-iframe-container"], "cookies": ["messagesutk"]},
]
