"""WebIntelPro Enterprise X - E-commerce Platform Fingerprints"""

FINGERPRINTS = [
    {"name": "WooCommerce", "category": "ecommerce", "headers": [],
     "meta": ["woocommerce"], "scripts": ["woocommerce", "wc-ajax", "plugins/woocommerce"],
     "inline": ["woocommerce_params", "wc_add_to_cart"], "dom": ["woocommerce", "wc-block"],
     "cookies": ["woocommerce_cart_hash", "woocommerce_items_in_cart"]},
    {"name": "Magento", "category": "ecommerce", "headers": ["x-magento"], "meta": [],
     "scripts": ["mage/", "requirejs/require.js", "static/version"],
     "inline": ["mage/cookies", "window.checkout"], "dom": ["data-mage-init"],
     "cookies": ["mage-cache-storage", "x-magento-vary"]},
    {"name": "BigCommerce", "category": "ecommerce", "headers": ["x-bc"], "meta": [],
     "scripts": ["cdn11.bigcommerce.com", "bigcommerce.com"], "inline": ["bigcommerce"],
     "dom": [], "cookies": ["shop_session_token"]},
    {"name": "PrestaShop", "category": "ecommerce", "headers": [], "meta": ["prestashop"],
     "scripts": ["prestashop"], "inline": ["prestashop"], "dom": [], "cookies": ["prestashop"]},
    {"name": "Squarespace Commerce", "category": "ecommerce", "headers": [], "meta": [],
     "scripts": ["squarespace", "sqsp.net", "static1.squarespace.com"],
     "inline": ["squarespace", "static.squarespace"], "dom": ["sqs-block"], "cookies": []},
    {"name": "Wix Stores", "category": "ecommerce", "headers": ["x-wix-request-id"],
     "meta": [], "scripts": ["static.parastorage.com", "wix.com"],
     "inline": ["wixbisession", "window.wix"], "dom": ["wix-"], "cookies": []},
    {"name": "Ecwid", "category": "ecommerce", "headers": [], "meta": [],
     "scripts": ["app.ecwid.com", "ecwid.com/script.js"],
     "inline": ["ecwid", "window.ecwid"], "dom": ["ecwid-"], "cookies": []},
    {"name": "Salesforce Commerce Cloud", "category": "ecommerce",
     "headers": ["x-is-", "dwsecuretoken"], "meta": [],
     "scripts": ["demandware", "commercecloud"], "inline": ["dw.ac", "demandware"],
     "dom": [], "cookies": ["dwanonymous_", "dwsid"]},
    {"name": "OpenCart", "category": "ecommerce", "headers": [], "meta": [],
     "scripts": ["catalog/view/", "index.php?route="], "inline": ["opencart"],
     "dom": [], "cookies": ["ocsessid"]},
    {"name": "Shopware", "category": "ecommerce", "headers": ["x-shopware"],
     "meta": ["shopware"], "scripts": ["shopware"], "inline": ["shopware"], "dom": [],
     "cookies": []},
    {"name": "Snipcart", "category": "ecommerce", "headers": [], "meta": [],
     "scripts": ["cdn.snipcart.com", "snipcart.js"], "inline": ["snipcart"],
     "dom": ["snipcart"], "cookies": []},
]
