"""WebIntelPro Enterprise X - Extra JS libraries & build tools."""
def j(name, scripts=(), inline=(), dom=(), cat="javascript"):
    return {"name": name, "category": cat, "headers": [], "meta": [],
            "scripts": list(scripts), "inline": list(inline), "dom": list(dom), "cookies": []}
FINGERPRINTS = [
    j("Stimulus", ["stimulus.js", "@hotwired/stimulus"], ["stimulus.application"], ["data-controller"]),
    j("Turbo", ["@hotwired/turbo", "turbo.min.js"], ["turbo:load"], ["data-turbo"]),
    j("HTMX", ["htmx.min.js", "htmx.org"], ["htmx.process"], ["hx-get", "hx-post"]),
    j("Lit", ["lit-element", "lit-html", "cdn.jsdelivr.net/npm/lit"], ["litelement"]),
    j("Stencil", ["stencil.js", "@stencil/core"], ["stenciljs"]),
    j("Qwik", ["@builder.io/qwik", "/build/q-"], ["qwikloader", "q:container"], ["q:container"]),
    j("Marko", ["marko/dist"], ["marko_component"]),
    j("Meteor", ["meteor.js", "/packages/meteor"], ["__meteor_runtime_config__"]),
    j("Ractive", ["ractive.js", "ractive.min.js"], ["new ractive"]),
    j("Knockout", ["knockout.js", "knockout-min.js"], ["ko.applybindings"], ["data-bind"]),
    j("Riot.js", ["riot.min.js", "riot+compiler"], ["riot.mount"]),
    j("Mithril", ["mithril.min.js", "mithril.js"], ["m.mount", "m.render"]),
    j("Aurelia", ["aurelia-bootstrapper"], ["aurelia"], ["aurelia-app"]),
    j("Turbolinks", ["turbolinks.js", "turbolinks.min.js"], ["turbolinks.visit"]),
    j("Barba.js", ["barba.min.js", "@barba/core"], ["barba.init"]),
    j("Framer Motion", ["framer-motion"], ["framermotion"]),
    j("Emotion", ["@emotion/react", "emotion.min.js"], ["__emotion"]),
    j("styled-components", ["styled-components"], ["__emotion", "sc-"], [" sc-"]),
    j("Immer", ["immer.min.js", "cdn.jsdelivr.net/npm/immer"], ["produce("]),
    j("Zustand", ["zustand"], ["zustand"]),
    j("MobX", ["mobx.min.js", "mobx/dist"], ["mobx.observable"]),
    j("Formik", ["formik"], ["formik"]),
    j("Yup", ["yup.min.js"], []),
    j("SWR", ["swr/dist"], ["useswr"]),
    j("React Query", ["@tanstack/react-query", "react-query"], ["queryclient"]),
    j("Flickity", ["flickity.pkgd", "flickity.min.js"], ["new flickity"], ["flickity-enabled"]),
    j("Glide.js", ["glide.min.js", "@glidejs/glide"], ["new glide"], ["glide__slide"]),
    j("Keen Slider", ["keen-slider"], ["keenslider"], ["keen-slider"]),
    j("Embla Carousel", ["embla-carousel"], ["emblacarousel"], ["embla__slide"]),
    j("Plyr", ["plyr.min.js", "plyr.io"], ["new plyr"], ["plyr"]),
    j("Shaka Player", ["shaka-player"], ["shaka.player"]),
    j("Dash.js", ["dash.all.min.js", "dashjs"], ["dashjs.mediaplayer"]),
    j("Reveal.js", ["reveal.js", "reveal.min.js"], ["reveal.initialize"], ["reveal"]),
    j("Turf.js", ["@turf/turf", "turf.min.js"], ["turf."]),
    j("Konva", ["konva.min.js", "konvajs"], ["new konva"]),
    j("Fabric.js", ["fabric.min.js", "fabricjs"], ["new fabric."]),
    j("Paper.js", ["paper.min.js", "paperjs"], ["paper.setup"]),
    j("p5.js", ["p5.min.js", "p5.js"], ["new p5"]),
    j("Matter.js", ["matter.min.js", "matter-js"], ["matter.engine"]),
    j("CodeMirror", ["codemirror.min.js", "codemirror"], ["codemirror("], ["cm-editor"]),
    j("Monaco Editor", ["monaco-editor"], ["monaco.editor"]),
    j("Quill", ["quill.min.js", "quilljs"], ["new quill"], ["ql-editor"]),
    j("TinyMCE", ["tinymce.min.js", "tinymce/tinymce"], ["tinymce.init"], ["mce-content-body"]),
    j("CKEditor", ["ckeditor.js", "ckeditor5"], ["ckeditor.create"], ["ck-editor"]),
    j("Turnstile Loader", ["cf-turnstile-response"], []),
    j("Turbopack Runtime", ["turbopack-"], ["__turbopack"], [], "build"),
    j("Bun", ["bun-"], ["bun.serve"], [], "build"),
    j("Deno Deploy", ["deno.land"], [], [], "build"),
]
