"""WebIntelPro Enterprise X - Additional specific fingerprints (v3)."""
def d(name, cat, headers=(), scripts=(), inline=(), dom=(), cookies=()):
    return {"name": name, "category": cat, "headers": list(headers), "meta": [],
            "scripts": list(scripts), "inline": list(inline), "dom": list(dom), "cookies": list(cookies)}
FINGERPRINTS = [
    d("Sanity Studio", "cms", scripts=["cdn.sanity.io/studio"], inline=["sanitystudio"]),
    d("Hygraph", "cms", scripts=["hygraph.com", "graphcms"], inline=["hygraph"]),
    d("Umami", "analytics", scripts=["umami.is/script.js", "/umami.js"], inline=["umami.track"]),
    d("Simple Analytics", "analytics", scripts=["scripts.simpleanalyticscdn.com"], inline=["sa_event"]),
    d("GoatCounter", "analytics", scripts=["gc.zgo.at/count.js"], inline=["goatcounter"]),
    d("Pirsch", "analytics", scripts=["api.pirsch.io/pirsch.js"], inline=["pirsch("]),
    d("Vercel Analytics", "analytics", scripts=["/_vercel/insights/script.js"], inline=["va("]),
    d("Cloudflare Insights", "analytics", scripts=["static.cloudflareinsights.com/beacon"], inline=["cfbeacon"]),
    d("Sentry Replay", "analytics", scripts=["sentry-replay"], inline=["replayintegration"]),
    d("Datadog Browser Logs", "analytics", scripts=["datadog-logs"], inline=["dd_logs"]),
    d("Segment (Analytics.js 2)", "analytics", scripts=["cdn.segment.com/analytics-next"], inline=["analytics.identify"]),
    d("Iubenda", "privacy", scripts=["cdn.iubenda.com"], inline=["_iub"]),
    d("Complianz", "privacy", scripts=["complianz"], inline=["cmplz"]),
    d("Klaro", "privacy", scripts=["kiprotect.com/klaro", "klaro.js"], inline=["klaro"]),
    d("Braze", "marketing", scripts=["js.appboycdn.com", "sdk.braze"], inline=["appboy", "braze.initialize"]),
    d("Iterable", "marketing", scripts=["cdn.iterable.com"], inline=["iterable"]),
    d("Customer.io", "marketing", scripts=["assets.customer.io"], inline=["_cio"]),
    d("Postscript", "marketing", scripts=["sdk.postscript.io"], inline=["postscript"]),
    d("Attentive", "marketing", scripts=["cdn.attn.tv"], inline=["attentive"]),
    d("Wunderkind", "marketing", scripts=["tag.wknd.ai", "bounceexchange.com"], inline=["bouncex"]),
    d("Nosto", "ecommerce", scripts=["connect.nosto.com"], inline=["nostojs"]),
    d("Dynamic Yield", "marketing", scripts=["cdn.dynamicyield.com"], inline=["dyapi"]),
    d("Rebuy", "ecommerce", scripts=["cdn.rebuyengine.com"], inline=["rebuy"]),
    d("Loox Reviews", "marketing", scripts=["loox.io/widget"], inline=["loox"]),
    d("Okendo", "marketing", scripts=["okendo.io"], inline=["okendo"]),
    d("Gorgias Convert", "ecommerce", scripts=["config.gorgias.chat/bundle"], inline=["gorgiaschat"]),
    d("Fera Reviews", "marketing", scripts=["cdn.fera.ai"], inline=["fera"]),
    d("Stamped.io", "marketing", scripts=["stamped.io/js"], inline=["stampedio"]),
    d("PowerReviews", "marketing", scripts=["ui.powerreviews.com"], inline=["powerreviews"]),
    d("Bold Subscriptions", "ecommerce", scripts=["cdn.boldapps.net/subscriptions"], inline=["boldsubscriptions"]),
]
