"""WebIntelPro Enterprise X - Web / Application Framework Fingerprints"""

FINGERPRINTS = [
    {"name": "Angular", "category": "framework", "headers": [], "meta": [],
     "scripts": ["ng-version", "zone.js", "polyfills."], "inline": ["ngdevmode"],
     "dom": ["ng-version", "_nghost", "_ngcontent", "ng-app"], "cookies": []},
    {"name": "AngularJS", "category": "framework", "headers": [], "meta": [],
     "scripts": ["angular.js", "angular.min.js"], "inline": ["angular.module"],
     "dom": ["ng-controller", "ng-binding", "ng-repeat"], "cookies": []},
    {"name": "Svelte", "category": "framework", "headers": [], "meta": [],
     "scripts": ["svelte"], "inline": [], "dom": ["svelte-"], "cookies": []},
    {"name": "SvelteKit", "category": "framework", "headers": [], "meta": [],
     "scripts": ["_app/immutable", "sveltekit"], "inline": ["__sveltekit"],
     "dom": [], "cookies": []},
    {"name": "Nuxt.js", "category": "framework", "headers": [], "meta": [],
     "scripts": ["_nuxt/", "nuxt"], "inline": ["__nuxt__", "window.__nuxt__"],
     "dom": ["__nuxt", "data-n-head"], "cookies": []},
    {"name": "Gatsby", "category": "framework", "headers": [], "meta": ["gatsby"],
     "scripts": ["gatsby"], "inline": ["___gatsby", "___loader"],
     "dom": ["___gatsby"], "cookies": [], "implies": ["React"]},
    {"name": "Astro", "category": "framework", "headers": [], "meta": ["astro"],
     "scripts": ["astro"], "inline": [], "dom": ["astro-island", "astro-"],
     "cookies": []},
    {"name": "Remix", "category": "framework", "headers": [], "meta": [],
     "scripts": ["remix"], "inline": ["__remixcontext", "__remixmanifest"],
     "dom": [], "cookies": [], "implies": ["React"]},
    {"name": "Ember.js", "category": "framework", "headers": [], "meta": [],
     "scripts": ["ember.min.js", "ember.debug.js", "/assets/ember"],
     "inline": ["ember.version", "enifed("],
     "dom": ["ember-application", "ember-view"], "cookies": []},
    {"name": "Backbone.js", "category": "framework", "headers": [], "meta": [],
     "scripts": ["backbone"], "inline": ["backbone.model", "backbone.view"],
     "dom": [], "cookies": []},
    {"name": "jQuery", "category": "framework", "headers": [], "meta": [],
     "scripts": ["jquery"], "inline": ["jquery(", "$(document).ready"],
     "dom": [], "cookies": []},
    {"name": "Alpine.js", "category": "framework", "headers": [], "meta": [],
     "scripts": ["alpinejs", "cdn.jsdelivr.net/npm/alpinejs"],
     "inline": ["alpine.start", "alpine.data"],
     "dom": ["x-data", "x-bind", "x-show"], "cookies": []},
    {"name": "Preact", "category": "framework", "headers": [], "meta": [],
     "scripts": ["preact"], "inline": ["__preact_devtools__"], "dom": [], "cookies": []},
    {"name": "Solid.js", "category": "framework", "headers": [], "meta": [],
     "scripts": ["solid-js"], "inline": ["_$hydration"], "dom": [], "cookies": []},
    {"name": "Django", "category": "framework", "headers": [], "meta": [],
     "scripts": [], "inline": ["csrfmiddlewaretoken"], "dom": [],
     "cookies": ["csrftoken", "django"]},
    {"name": "Ruby on Rails", "category": "framework",
     "headers": ["mod_rails", "phusion passenger"], "meta": [], "scripts": [],
     "inline": ["csrf-token", "authenticity_token"], "dom": [],
     "cookies": ["_session_id"]},
    {"name": "Express", "category": "framework",
     "headers": ["express", "x-powered-by:express"], "meta": [], "scripts": [],
     "inline": [], "dom": [], "cookies": ["connect.sid"]},
    {"name": "ASP.NET", "category": "framework",
     "headers": ["asp.net", "x-aspnet-version", "x-aspnetmvc-version"], "meta": [],
     "scripts": [], "inline": ["__viewstate", "__eventvalidation"],
     "dom": ["__viewstate"], "cookies": ["asp.net_sessionid"]},
    {"name": "Flask", "category": "framework", "headers": ["werkzeug"], "meta": [],
     "scripts": [], "inline": [], "dom": [], "cookies": []},
    {"name": "Symfony", "category": "framework",
     "headers": ["x-debug-token", "x-debug-token-link"], "meta": ["symfony"],
     "scripts": [], "inline": [], "dom": [], "cookies": ["symfony"]},
    {"name": "Laravel", "category": "framework", "headers": [], "meta": ["csrf-token"],
     "scripts": [], "inline": ["laravel"], "dom": [],
     "cookies": ["laravel_session", "xsrf-token"]},
    {"name": "CodeIgniter", "category": "framework", "headers": [], "meta": [],
     "scripts": [], "inline": [], "dom": [], "cookies": ["ci_session"]},
    {"name": "Spring", "category": "framework", "headers": ["x-application-context"],
     "meta": [], "scripts": [], "inline": [], "dom": [], "cookies": ["jsessionid"]},
]
