"""WebIntelPro Enterprise X - JavaScript Library Fingerprints"""

def _fp(name, scripts=(), inline=(), dom=(), category="javascript"):
    return {"name": name, "category": category, "headers": [], "meta": [],
            "scripts": list(scripts), "inline": list(inline), "dom": list(dom),
            "cookies": []}

FINGERPRINTS = [
    _fp("Lodash", ["lodash.min.js", "lodash.js", "cdn.jsdelivr.net/npm/lodash"], ["_.chunk", "lodash.version"]),
    _fp("Underscore.js", ["underscore.js", "underscore-min.js"], ["_.each"]),
    _fp("Moment.js", ["moment.min.js", "moment.js", "momentjs"], ["moment("]),
    _fp("Day.js", ["dayjs", "day.js"], ["dayjs("]),
    _fp("date-fns", ["date-fns"], []),
    _fp("Axios", ["axios.min.js", "axios/dist", "cdn.jsdelivr.net/npm/axios"], ["axios.get", "axios.create"]),
    _fp("D3.js", ["d3.min.js", "d3.v", "d3js.org"], ["d3.select"]),
    _fp("Three.js", ["three.min.js", "three.module.js", "threejs"], ["three.webglrenderer", "new three."]),
    _fp("Chart.js", ["chart.min.js", "chart.js", "cdn.jsdelivr.net/npm/chart.js"], ["new chart("]),
    _fp("Highcharts", ["highcharts.js", "highcharts.com"], ["highcharts.chart"]),
    _fp("ApexCharts", ["apexcharts"], ["new apexcharts"]),
    _fp("ECharts", ["echarts.min.js", "echarts"], ["echarts.init"]),
    _fp("GSAP", ["gsap.min.js", "gsap", "greensock"], ["gsap.to", "tweenmax"]),
    _fp("Swiper", ["swiper-bundle", "swiper.min.js"], ["new swiper"], ["swiper-slide", "swiper-container"]),
    _fp("Slick", ["slick.min.js", "slick-carousel"], [".slick("], ["slick-slider"]),
    _fp("Owl Carousel", ["owl.carousel"], [".owlcarousel"], ["owl-carousel"]),
    _fp("AOS", ["aos.js", "aos.min.js"], ["aos.init"], ["data-aos"]),
    _fp("Lottie", ["lottie.min.js", "lottie-player", "bodymovin"], ["lottie.loadanimation"], ["lottie-player"]),
    _fp("Video.js", ["video.min.js", "videojs"], ["videojs("], ["video-js"]),
    _fp("hls.js", ["hls.min.js", "hls.js"], ["new hls("]),
    _fp("Socket.IO", ["socket.io.js", "socket.io/socket.io", "socket.io-client"], ["io.connect"]),
    _fp("PixiJS", ["pixi.min.js", "pixi.js"], ["new pixi."]),
    _fp("Phaser", ["phaser.min.js", "phaser.js"], ["new phaser.game"]),
    _fp("MathJax", ["mathjax", "tex-mml"], ["mathjax"]),
    _fp("Prism.js", ["prism.js", "prism.min.js", "prismjs"], [], [
        "language-javascript", "language-python", "language-css",
        "language-markup", "language-bash", "language-json",
        "language-typescript", "language-jsx", "language-yaml",
        "language-sql", "language-none", "line-numbers",
    ]),
    _fp("highlight.js", ["highlight.min.js", "highlight.js", "hljs"], ["hljs.highlight"], ["hljs"]),
    _fp("Modernizr", ["modernizr"], ["modernizr"], ["no-js"]),
    _fp("Popper.js", ["popper.min.js", "popper.js", "@popperjs"], ["createpopper"]),
    _fp("Tippy.js", ["tippy.js", "tippy.min.js"], ["tippy("]),
    _fp("jQuery UI", ["jquery-ui", "jqueryui"], [], ["ui-widget", "ui-draggable"]),
    _fp("Redux", ["redux.min.js", "redux.js"], ["createstore", "__redux_devtools"]),
    _fp("RxJS", ["rxjs"], ["rxjs.observable"]),
    _fp("Handlebars", ["handlebars.js", "handlebars.min.js"], ["handlebars.compile"]),
    _fp("Mustache.js", ["mustache.js", "mustache.min.js"], ["mustache.render"]),
    _fp("Leaflet", ["leaflet.js", "leaflet.min.js", "unpkg.com/leaflet"], ["l.map"], ["leaflet-container"]),
    _fp("Mapbox GL", ["mapbox-gl", "mapbox.js"], ["mapboxgl."]),
    _fp("Google Maps", ["maps.googleapis.com/maps"], ["google.maps"]),
    _fp("Fuse.js", ["fuse.js", "fuse.min.js"], ["new fuse("]),
    _fp("Splide", ["splide.min.js", "splidejs"], ["new splide"], ["splide__slide"]),
    _fp("Marked", ["marked.min.js", "marked.js"], ["marked.parse"]),
    _fp("Anime.js", ["anime.min.js", "animejs"], ["anime("]),
    _fp("ScrollMagic", ["scrollmagic"], ["new scrollmagic"]),
    _fp("Isotope", ["isotope.pkgd", "isotope.min.js"], ["new isotope"], ["isotope"]),
]
