"""WebIntelPro Enterprise X - Marketing / Automation / Ad-Tech Fingerprints"""

FINGERPRINTS = [
    {"name": "HubSpot", "category": "marketing", "headers": [], "meta": [],
     "scripts": ["js.hs-scripts.com", "js.hsforms.net", "hs-analytics.net"],
     "inline": ["_hsq", "hbspt"], "dom": [], "cookies": ["hubspotutk", "__hstc"]},
    {"name": "Marketo", "category": "marketing", "headers": [], "meta": [],
     "scripts": ["munchkin.marketo.net", "marketo.com"],
     "inline": ["munchkin.init", "mktoforms2"], "dom": [], "cookies": ["_mkto_trk"]},
    {"name": "Mailchimp", "category": "marketing", "headers": [], "meta": [],
     "scripts": ["chimpstatic.com", "list-manage.com", "mailchimp"],
     "inline": ["mc_embed", "mcvalidate"], "dom": ["mc_embed_signup"], "cookies": []},
    {"name": "Klaviyo", "category": "marketing", "headers": [], "meta": [],
     "scripts": ["static.klaviyo.com", "klaviyo.js"], "inline": ["klaviyo", "_learnq"],
     "dom": ["klaviyo-form"], "cookies": ["__kla_id"]},
    {"name": "Segment", "category": "marketing", "headers": [], "meta": [],
     "scripts": ["cdn.segment.com", "segment.io"],
     "inline": ["analytics.load", "window.analytics"], "dom": [],
     "cookies": ["ajs_anonymous_id", "ajs_user_id"]},
    {"name": "Salesforce Pardot", "category": "marketing", "headers": [], "meta": [],
     "scripts": ["pi.pardot.com", "pardot"], "inline": ["piaid", "pardot"], "dom": [],
     "cookies": ["visitor_id"]},
    {"name": "ActiveCampaign", "category": "marketing", "headers": [], "meta": [],
     "scripts": ["activehosted.com", "prod.activehosted.com"],
     "inline": ["vgo(", "activecampaign"], "dom": [], "cookies": []},
    {"name": "Facebook Pixel", "category": "marketing", "headers": [], "meta": [],
     "scripts": ["connect.facebook.net", "fbevents.js"], "inline": ["fbq(", "fbq('init'"],
     "dom": [], "cookies": ["_fbp", "_fbc"]},
    {"name": "Google Ads", "category": "marketing", "headers": [], "meta": [],
     "scripts": ["googleadservices.com", "googlesyndication.com"],
     "inline": ["google_conversion_id"], "dom": [], "cookies": ["_gcl_au"]},
    {"name": "LinkedIn Insight", "category": "marketing", "headers": [], "meta": [],
     "scripts": ["snap.licdn.com", "px.ads.linkedin.com"],
     "inline": ["_linkedin_partner_id", "lintrk"], "dom": [], "cookies": ["li_fat_id"]},
    {"name": "Twitter Pixel", "category": "marketing", "headers": [], "meta": [],
     "scripts": ["static.ads-twitter.com", "analytics.twitter.com"],
     "inline": ["twq(", "twq('init'"], "dom": [], "cookies": ["personalization_id"]},
    {"name": "Optimizely", "category": "marketing", "headers": [], "meta": [],
     "scripts": ["cdn.optimizely.com", "optimizely.js"],
     "inline": ["window.optimizely", "optimizely.push"], "dom": [], "cookies": []},
]
