"""WebIntelPro Enterprise X - Payment Gateway / Processor Fingerprints"""

FINGERPRINTS = [
    {"name": "Stripe", "category": "payment",
     # A CSP / Link header that whitelists js.stripe.com is a strong, low-FP
     # signal the site integrates Stripe even when the current page doesn't
     # embed the script (e.g. stripe.com's own marketing homepage).
     "headers": ["js.stripe.com"], "meta": [],
     "scripts": ["js.stripe.com", "stripe.com/v3"], "inline": ["stripe(", "window.stripe"],
     "dom": ["stripe-button", "__privatestripeframe"],
     "cookies": ["__stripe_mid", "__stripe_sid"]},
    {"name": "PayPal", "category": "payment", "headers": [], "meta": [],
     "scripts": ["paypal.com/sdk/js", "paypalobjects.com", "paypal.com/js"],
     "inline": ["paypal.buttons", "window.paypal"], "dom": ["paypal-button"], "cookies": []},
    {"name": "Braintree", "category": "payment", "headers": [], "meta": [],
     "scripts": ["js.braintreegateway.com", "braintree"],
     "inline": ["braintree.client", "window.braintree"], "dom": [], "cookies": []},
    {"name": "Square", "category": "payment", "headers": [], "meta": [],
     "scripts": ["squareup.com", "js.squareup.com"],
     "inline": ["sqpaymentform", "window.square"], "dom": [], "cookies": []},
    {"name": "Adyen", "category": "payment", "headers": [], "meta": [],
     "scripts": ["checkoutshopper", "adyen.com"],
     "inline": ["adyencheckout", "window.adyen"], "dom": ["adyen-checkout"], "cookies": []},
    {"name": "Klarna", "category": "payment", "headers": [], "meta": [],
     "scripts": ["klarna.com", "x.klarnacdn.net"], "inline": ["klarna", "window.klarna"],
     "dom": ["klarna-"], "cookies": []},
    {"name": "Afterpay", "category": "payment", "headers": [], "meta": [],
     "scripts": ["afterpay.com", "static.afterpay.com"], "inline": ["afterpay"],
     "dom": ["afterpay-"], "cookies": []},
    {"name": "Amazon Pay", "category": "payment", "headers": [], "meta": [],
     "scripts": ["static-na.payments-amazon.com", "amazonpay"],
     "inline": ["amazon.pay", "amazonpaymentsready"], "dom": [], "cookies": []},
    {"name": "Razorpay", "category": "payment", "headers": [], "meta": [],
     "scripts": ["checkout.razorpay.com", "razorpay.com"],
     "inline": ["razorpay", "new razorpay"], "dom": [], "cookies": []},
    {"name": "Authorize.Net", "category": "payment", "headers": [], "meta": [],
     "scripts": ["js.authorize.net", "authorize.net"], "inline": ["acceptjs", "authorizenet"],
     "dom": [], "cookies": []},
    {"name": "Checkout.com", "category": "payment", "headers": [], "meta": [],
     "scripts": ["cdn.checkout.com", "checkout.frames.js"],
     "inline": ["frames.init", "checkout.com"], "dom": [], "cookies": []},
    {"name": "Mollie", "category": "payment", "headers": [], "meta": [],
     "scripts": ["js.mollie.com", "mollie.com"], "inline": ["mollie(", "window.mollie"],
     "dom": [], "cookies": []},
]
