"""WebIntelPro Enterprise X - Security / WAF / Bot-Protection Fingerprints"""

FINGERPRINTS = [
    {"name": "Google reCAPTCHA", "category": "security", "headers": [], "meta": [],
     "scripts": ["recaptcha/api.js", "gstatic.com/recaptcha", "google.com/recaptcha"],
     "inline": ["grecaptcha"], "dom": ["g-recaptcha"], "cookies": []},
    {"name": "hCaptcha", "category": "security", "headers": [], "meta": [],
     "scripts": ["hcaptcha.com/1/api.js", "js.hcaptcha.com"], "inline": ["hcaptcha"],
     "dom": ["h-captcha"], "cookies": []},
    {"name": "Cloudflare Turnstile", "category": "security", "headers": [], "meta": [],
     "scripts": ["challenges.cloudflare.com/turnstile"], "inline": ["turnstile"],
     "dom": ["cf-turnstile"], "cookies": []},
    {"name": "Cloudflare Bot Management", "category": "security",
     "headers": ["cf-ray", "cf-mitigated"], "meta": [], "scripts": [], "inline": [],
     "dom": [], "cookies": ["__cf_bm", "cf_clearance"]},
    {"name": "Sucuri", "category": "security",
     "headers": ["x-sucuri-id", "x-sucuri-cache", "sucuri"], "meta": [],
     "scripts": [], "inline": [], "dom": [], "cookies": []},
    {"name": "Imperva Incapsula", "category": "security",
     "headers": ["x-iinfo", "x-cdn:incapsula"], "meta": [], "scripts": [],
     "inline": ["incapsula"], "dom": [], "cookies": ["incap_ses", "visid_incap"]},
    {"name": "Akamai Bot Manager", "category": "security",
     "headers": ["akamai", "x-akamai"], "meta": [], "scripts": [],
     "inline": ["bmak", "_abck"], "dom": [], "cookies": ["_abck", "ak_bmsc"]},
    {"name": "DataDome", "category": "security", "headers": ["x-datadome", "x-dd-b"],
     "meta": [], "scripts": ["js.datadome.co"], "inline": ["datadome"], "dom": [],
     "cookies": ["datadome"]},
    {"name": "PerimeterX", "category": "security", "headers": ["x-px"], "meta": [],
     "scripts": ["client.perimeterx.net"], "inline": ["_pxappid", "window._px"],
     "dom": [], "cookies": ["_px", "_pxvid"]},
    {"name": "Wordfence", "category": "security", "headers": [], "meta": [],
     "scripts": ["wordfence"], "inline": ["wordfence"], "dom": [],
     "cookies": ["wfvt_", "wf_loginalerted"]},
    {"name": "HSTS", "category": "security", "headers": ["strict-transport-security"],
     "meta": [], "scripts": [], "inline": [], "dom": [], "cookies": []},
    {"name": "Content Security Policy", "category": "security",
     "headers": ["content-security-policy"], "meta": ["content-security-policy"],
     "scripts": [], "inline": [], "dom": [], "cookies": []},
]
